# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application_history_client.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import Security_pb2
import yarn_service_protos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='application_history_client.proto',
  package='hadoop.yarn',
  serialized_pb='\n application_history_client.proto\x12\x0bhadoop.yarn\x1a\x0eSecurity.proto\x1a\x19yarn_service_protos.proto2\xcd\x08\n!ApplicationHistoryProtocolService\x12u\n\x14getApplicationReport\x12-.hadoop.yarn.GetApplicationReportRequestProto\x1a..hadoop.yarn.GetApplicationReportResponseProto\x12\x66\n\x0fgetApplications\x12(.hadoop.yarn.GetApplicationsRequestProto\x1a).hadoop.yarn.GetApplicationsResponseProto\x12\x8a\x01\n\x1bgetApplicationAttemptReport\x12\x34.hadoop.yarn.GetApplicationAttemptReportRequestProto\x1a\x35.hadoop.yarn.GetApplicationAttemptReportResponseProto\x12{\n\x16getApplicationAttempts\x12/.hadoop.yarn.GetApplicationAttemptsRequestProto\x1a\x30.hadoop.yarn.GetApplicationAttemptsResponseProto\x12o\n\x12getContainerReport\x12+.hadoop.yarn.GetContainerReportRequestProto\x1a,.hadoop.yarn.GetContainerReportResponseProto\x12`\n\rgetContainers\x12&.hadoop.yarn.GetContainersRequestProto\x1a\'.hadoop.yarn.GetContainersResponseProto\x12s\n\x12getDelegationToken\x12-.hadoop.common.GetDelegationTokenRequestProto\x1a..hadoop.common.GetDelegationTokenResponseProto\x12y\n\x14renewDelegationToken\x12/.hadoop.common.RenewDelegationTokenRequestProto\x1a\x30.hadoop.common.RenewDelegationTokenResponseProto\x12|\n\x15\x63\x61ncelDelegationToken\x12\x30.hadoop.common.CancelDelegationTokenRequestProto\x1a\x31.hadoop.common.CancelDelegationTokenResponseProtoB@\n\x1corg.apache.hadoop.yarn.protoB\x1a\x41pplicationHistoryProtocol\x88\x01\x01\xa0\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\034org.apache.hadoop.yarn.protoB\032ApplicationHistoryProtocol\210\001\001\240\001\001')
# @@protoc_insertion_point(module_scope)
